FROM gitpod/workspace-java-11:2024-06-26-08-49-45

ENV JAVA_HOME "/home/gitpod/.sdkman/candidates/java/current"

USER root    

# Just matched `app/build.gradle` | 33
ENV ANDROID_COMPILE_SDK "28" 
# Just matched `app/build.gradle`
ENV ANDROID_BUILD_TOOLS "29.0.2"
# Version from https://developer.android.com/studio/releases/sdk-tools
ENV ANDROID_SDK_TOOLS "24.4.1"
# ENV VERSION_SDK_TOOLS "4333796" | 7583922_latest | 9123335_latest 
ENV VERSION_SDK_TOOLS "9123335_latest"
ENV ANDROID_HOME "/home/gitpod/sdk"
ENV PATH "$PATH:${ANDROID_HOME}/tools"

RUN mkdir -p $ANDROID_HOME

# install OS packages
RUN apt-get --quiet update --yes
RUN apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 build-essential ruby ruby-dev vim-common

#https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
RUN curl -s https://dl.google.com/android/repository/commandlinetools-linux-${VERSION_SDK_TOOLS}.zip > /sdk.zip && \
    unzip /sdk.zip -d $ANDROID_HOME && \
    rm -v /sdk.zip

RUN mkdir -p $ANDROID_HOME/licenses/
ADD licenses/* $ANDROID_HOME/licenses/

#accept licenses
RUN cp -r $ANDROID_HOME/licenses/. $ANDROID_HOME
RUN mkdir /tools
RUN mv $ANDROID_HOME/cmdline-tools/* /tools/
RUN mkdir -p $ANDROID_HOME/cmdline-tools/latest
RUN mv /tools/* $ANDROID_HOME/cmdline-tools/latest/

RUN yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

ADD packages.txt $ANDROID_HOME
RUN mkdir -p /root/.android && \
  touch /root/.android/repositories.cfg && \
  ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --update
RUN while read -r package; do PACKAGES="${PACKAGES}${package} "; done < $ANDROID_HOME/packages.txt && \
    ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager ${PACKAGES}

# install Fastlane
RUN gem install bundler
COPY Gemfile .
RUN bundle update

#install firebase cli
RUN curl -sL firebase.tools | bash


# Download Flutter SDK
WORKDIR /home/gitpod
RUN git clone -b 3.22.2 https://github.com/flutter/flutter.git


# install vnc
RUN install-packages \
	tigervnc-standalone-server tigervnc-xorg-extension \
	dbus dbus-x11 gnome-keyring xfce4 xfce4-terminal \
	xdg-utils x11-xserver-utils pip

# Install novnc and numpy module for it
RUN git clone --depth 1 https://github.com/novnc/noVNC.git /opt/novnc \
	&& git clone --depth 1 https://github.com/novnc/websockify /opt/novnc/utils/websockify \
	&& find /opt/novnc -type d -name '.git' -exec rm -rf '{}' + \
	&& sudo -H pip3 install numpy
COPY novnc-index.html /opt/novnc/index.html

# Add VNC startup script
COPY gp-vncsession /usr/bin/
RUN chmod 0755 /usr/bin/gp-vncsession \
	&& printf '%s\n' 'export DISPLAY=:0' \
	'test -e "$GITPOD_REPO_ROOT" && /usr/bin/gp-vncsession' >> "$HOME/.bashrc"

# Add X11 dotfiles
COPY --chown=gitpod:gitpod .xinitrc $HOME/    

# chrome and basic render font
# google-chrome
# misc deps for electron and puppeteer to run
RUN cd /tmp && glink="https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb" \
	&& wget -q "$glink" \
	&& install-packages libasound2-dev libgtk-3-dev libnss3-dev \
	fonts-noto fonts-noto-cjk ./"${glink##*/}" \
	\
	# OLD: && ln -srf /usr/bin/chromium /usr/bin/google-chrome
	# OLD: To make ungoogled_chromium discoverable by tools like flutter
	&& ln -srf /usr/bin/google-chrome /usr/bin/chromium \
	\
	# Extra chrome tweaks
	## Disables welcome screen
	&& t="$HOME/.config/google-chrome/First Run" && sudo -u gitpod mkdir -p "${t%/*}" && sudo -u gitpod touch "$t" \
	## Disables default browser prompt
	&& t="/etc/opt/chrome/policies/managed/managed_policies.json" && mkdir -p "${t%/*}" && printf '{ "%s": %s }\n' DefaultBrowserSettingEnabled false > "$t"

# For Qt WebEngine on docker
ENV QTWEBENGINE_DISABLE_SANDBOX 1

ENV PATH="$PATH:/home/gitpod/flutter/bin:/home/gitpod/sdk/platform-tools"

RUN chown -R gitpod /home/gitpod/
USER gitpod 