FROM gitpod/workspace-full-vnc:2024-06-26-08-49-45

ENV CYPRESS_CACHE_FOLDER=/workspace/.cypress-cache

# Install Cypress dependencies
RUN sudo apt-get update \
    && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    libgtk2.0-0 \
    libgtk-3-0 \
    libnotify-dev \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb \
    && sudo rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME="/home/gitpod/.sdkman/candidates/java/11.0.23.fx-zulu"
USER root    

# Just matched `app/build.gradle` | 33
ENV ANDROID_COMPILE_SDK "28" 
# Just matched `app/build.gradle`
ENV ANDROID_BUILD_TOOLS "29.0.2"
# Version from https://developer.android.com/studio/releases/sdk-tools
ENV ANDROID_SDK_TOOLS "24.4.1"
# ENV VERSION_SDK_TOOLS "4333796" | 7583922_latest | 9123335_latest 
ENV VERSION_SDK_TOOLS "9123335_latest"
ENV ANDROID_HOME "/home/gitpod/sdk"
ENV PATH "$PATH:${ANDROID_HOME}/tools"

RUN mkdir -p $ANDROID_HOME

# install OS packages
RUN apt-get --quiet update --yes
RUN apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 build-essential ruby ruby-dev
# We use this for xxd hex->binary
RUN apt-get --quiet install --yes vim-common

#https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
RUN curl -s https://dl.google.com/android/repository/commandlinetools-linux-${VERSION_SDK_TOOLS}.zip > /sdk.zip && \
    unzip /sdk.zip -d $ANDROID_HOME && \
    rm -v /sdk.zip

RUN mkdir -p $ANDROID_HOME/licenses/
ADD licenses/* $ANDROID_HOME/licenses/

#accept licenses
RUN mkdir -p $ANDROID_HOME/cmdline-tools/latest
RUN cp -r $ANDROID_HOME/licenses/. $ANDROID_HOME
RUN ls -al $ANDROID_HOME
RUN mkdir /tools
RUN cp -r $ANDROID_HOME/cmdline-tools/. /tools/
RUN cp -r /tools/. $ANDROID_HOME/cmdline-tools/latest/
RUN ls -al $ANDROID_HOME/cmdline-tools/latest/bin

RUN yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

ADD packages.txt $ANDROID_HOME
RUN mkdir -p /root/.android && \
  touch /root/.android/repositories.cfg && \
  ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --update
RUN while read -r package; do PACKAGES="${PACKAGES}${package} "; done < $ANDROID_HOME/packages.txt && \
    ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager ${PACKAGES}

# install Fastlane
RUN gem install bundler
COPY Gemfile .
RUN bundle update

#install firebase cli
RUN curl -sL firebase.tools | bash

# install plugins
#RUN fastlane add_plugin firebase_app_distribution

# Download Flutter SDK
WORKDIR /home/gitpod
RUN git clone -b 3.22.2 https://github.com/flutter/flutter.git

# install tailscale for networking
# RUN curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
# RUN curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
RUN curl -fsSL https://tailscale.com/install.sh | sh

RUN apt-get update && apt-get install -y tailscale     
RUN apt-get install -y jq

ENV PATH="$PATH:/home/gitpod/flutter/bin:/home/gitpod/sdk/platform-tools"

# Create the gitpod user. UID must be 33333.
RUN useradd -l -u 33333 -G sudo -md /home/gitpod -s /bin/bash -p gitpod gitpod

RUN chown -R gitpod /home/gitpod/
USER gitpod    
# 11.0.23    